### ISSUE TITLE
More elaborate example of using Custom Form components?

### ISSUE THREAD

**Issue by peterlazar1993** [julianocomg/react-native-form#10]
What properties are required in the customFields object? I was hoping to use this component to get the value of a custom picker. The picker has a state property called `selected` which is the value of this picker. How should I go about implementing this functionality?

**Comment by julianocomg** [comment]
@peterlazar1993 You don't need to control the state by yourself, just put the Picker inside the `<Form>` component, like this:

```js
import Form from 'react-native-form'
import {Picker} from 'react-native'

<Form ref="peterForm">
   <Picker type="Picker" name="myPicker" />
</Form>
```

So you can do:
```js 
this.refs.peterForm.getValues().myPicker
```

**Comment by julianocomg** [comment]
@peterlazar1993 And for custom fields:

```js
var customFields = {
  'PeterPicker': {
    controlled: true,
    valueProp: 'selectedValue',
    callbackProp: 'onValueChange',
  }
}

<Form ref="peterForm" customFields={customFields}>
  <PeterPicker type="PeterPicker" name="myPicker" />
</Form>
```

**Comment by peterlazar1993** [comment]
What is the callbackProp? I think this will be easier if I could screen share with you.

**Comment by julianocomg** [comment]
callbackProp is the prop called by the component when the value changes, in this case, `onValueChange`. See: https://facebook.github.io/react-native/docs/picker.html#onvaluechange

But we already have the native react-native inputs: https://github.com/julianocomg/react-native-form/blob/master/form.js#L43-L77

**Comment by peterlazar1993** [comment]
This is the custom picker let's say, I want to be able to access the `selected` property from the state, how would I go about this?
https://gist.github.com/peterlazar1993/c9b092bb2fe641fafcaf2f0a150161a9

**Comment by jucastilhoduarte** [comment]
The selected value always come from top, so use props instead of state, like this:

``` js
export default class EmojiStrip extends Component {
  constructor(props) {
    super(props);
    this.emojis = ['smiley', 'neutral_face', 'disappointed', 'x'];
  }

  static defaultProps = {
    selected: 'hello',
    onSelectEmoji: () => {}
  };

  isEmojiSelected = (emoji) => {
    if (this.props.selected === emoji) {
      return true;
    }
    return false;
  }

  renderEmojis = () => this.emojis.map((emoji, index) =>
    <Emoji
      key={index}
      emoji={emoji}
      enabled={this.isEmojiSelected(emoji)}
      onSelectEmoji={this.props.onSelectEmoji}
    />
  );

  render() {
    return (
      <View style={styles.container}>
        {
          this.renderEmojis()
        }
      </View>
    );
  }
}
```

Define the emoji custom field:

``` js
var customFields = {
  'EmojiStrip': {
    controlled: true,
    valueProp: 'selected',
    callbackProp: 'onSelectEmoji',
  }
}

<Form ref="form" customFields={customFields}>
  <EmojiStrip type="EmojiStrip" name="emoji" selected="smiley" />
</Form>
```

Get the value:

``` js
this.refs.form.getValues().emoji
```

**Comment by peterlazar1993** [comment]
I got it now :), So I shouldn't control the selected value myself instead let the `Form` component manage it. Thanks, this library will save me a ton of time. I'll take a good look at how it is working.

**Comment by peterlazar1993** [comment]
There's another problem now, unless `EmojiStrip` is a direct child of `Form`, I am not able to extract value from it. Custom fields cannot be nested?

**Comment by jucastilhoduarte** [comment]
Can you paste your code here?

**Comment by peterlazar1993** [comment]
PracticeDetails is the parent which will hold multiple custom form fields.
https://gist.github.com/peterlazar1993/2ad88471be5afbcfc50a4903d6ebff83

**Comment by jucastilhoduarte** [comment]
Yeah.. We only have support for deep elements if they are form's direct children, but you can do something like this: https://gist.github.com/julianocomg/125c25b985fe8e3e2b773316171fad9d

Or maybe you can put a `<Form>` inside every child of PraticeDetails and expose a function with .getValues() etc

**Comment by peterlazar1993** [comment]
The first approach works. Thank you 👍
