### ISSUE TITLE
Sample form

### ISSUE THREAD

**Issue by mayankkedia** [julianocomg/react-native-form#11]
Hello,

Can you please share an example of a form with a few fields created and some screenshots.

Cheers

**Comment by jucastilhoduarte** [comment]
Hi @mayankkedia, the "fields" are the same of the react-native docs, like `Slider`, `Switch`, `TextInput` etc.

You just need to create a `<Form>` and put any of these inside it, and then you can get all the values with one single method.

``` js
import {TextInput} from 'react-native'
import Form from 'react-native-form'

<Form ref="form">
  <View>
    <TextInput type="TextInput" name="mayankkedia" />
  </View>
</Form>
```

And now you can call `this.refs.form.getValues()` that will return an object like this:

``` js
{
   mayankkedia: "some value that you have inputted"
}
```

**Comment by mayankkedia** [comment]
Thank you for the quick response. I assume the actual styling and layout to make it look like a form say a setting page like iOS or android for instance is something that we would have to do as part of styling - is that right?

After modifying the code to work with ES6 I don't see any UI elements on the screen - but debugging it suggests that the control was created alright.

**Comment by temitope** [comment]
@mayankkedia yes you are right, it would be nice to find a form stylesheet as a starter
