### ISSUE TITLE
Unexpected token >

### ISSUE THREAD

**Issue by niftylettuce** [julianocomg/react-native-form#2]
I get a weird unexpected token error with this package

**Comment by jucastilhoduarte** [comment]
Can you paste the entire terminal message here?

**Comment by niftylettuce** [comment]
![screen shot 2015-10-18 at 3 02 54 pm](https://github-cloud.s3.amazonaws.com/assets/523141/10565950/5f873150-75a9-11e5-8cbf-c79795433997.png)

**Comment by niftylettuce** [comment]
```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 */
'use strict';

var React = require('react-native');

var Form = require('react-native-form');

console.log('Form', Form);
```

**Comment by niftylettuce** [comment]
The error is occuring on this line of code https://github.com/julianocomg/react-native-form/blob/master/index.js#L67

**Comment by andreyvital** [comment]
@niftylettuce do you think it's because of `element =>` instead of `(element) =>`?

**Comment by niftylettuce** [comment]
That didn't seem to work - I made the change locally and it didn't work.

**Comment by niftylettuce** [comment]
Parenthesis are optional if there's only one argument per https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

**Comment by niftylettuce** [comment]
I also get the error here:

``` js
props[allowedField.callbackProp] = (value) => {
```

**Comment by niftylettuce** [comment]
I fixed it by making the changes to normal ES5 syntax, not sure if this is the proper way though.

``` js
  createFormFields: function(elements) {
    return React.Children.map(elements, function(element) {
      var fieldType = element.type.displayName;
      var fieldName = element.props.name;
      var allowedField = this.getAllowedFormFieldTypes()[fieldType];

      var isValidField = (allowedField && fieldName);
      var props = {};

      if (isValidField) {
        props[allowedField.callbackProp] = function(value) {
          this.persistFieldValue(fieldName, value)
          var proxyCallback = element.props[allowedField.callbackProp]

          if (typeof proxyCallback === 'function') {
            proxyCallback(value)
          }
        }
      }

      if (isValidField && !this.values[fieldName]) {
        this.persistFieldValue(fieldName, (element.props[allowedField.defaultValueProp] || element.props.value));
      }

      props.children = this.createFormFields(element.props.children);
      return React.cloneElement(element, props);
    })
  },
```

**Comment by andreyvital** [comment]
Crystal. Well, that's right, I think that RN packager doesn't transpile required modules, so fat arrows aren't converted to `function(...)`.

**Comment by jucastilhoduarte** [comment]
@niftylettuce can you update your npm package to 0.1.4 and test again?

**Comment by niftylettuce** [comment]
```
return React.Children.map(elements,function(){
var fieldType=element.type.displayName;
```

Needs to have `function(element)`

Please unpublish 0.1.4 and publish 0.1.5 with this fix? @julianocomg @CentaurWarchief

**Comment by jucastilhoduarte** [comment]
@niftylettuce Sorry for taking this long to fix all this simple issues, I was traveling :sun_with_face: 
Please update your package to `0.1.5` and test again.

**Comment by niftylettuce** [comment]
All good no worries!

**Comment by niftylettuce** [comment]
@julianocomg Can you take a look into this?  Forgot to share the other day.  I still get a weird error.

![screen shot 2015-10-22 at 2 53 59 pm](https://cloud.githubusercontent.com/assets/523141/10675182/c6c4519c-78cc-11e5-8d20-affda8e1f5a0.png)

**Comment by jucastilhoduarte** [comment]
@niftylettuce can you paste your entire code here?

**Comment by niftylettuce** [comment]
Ah!  It does not allow `<Button>` inside a `<Form>` is the issue I think.

**Comment by niftylettuce** [comment]
![screen shot 2015-10-22 at 3 02 55 pm](https://cloud.githubusercontent.com/assets/523141/10675436/204fc8da-78ce-11e5-8eed-e6d4f090bfff.png)
![screen shot 2015-10-22 at 3 02 50 pm](https://cloud.githubusercontent.com/assets/523141/10675437/20506e7a-78ce-11e5-83c1-b4f20f14d0d9.png)

**Comment by niftylettuce** [comment]
The output of `console.log` above is `// element Go` showing that the element is a string not an object and doesn't have a type/props/displayName/name properties.

**Comment by niftylettuce** [comment]
Basically just plug in `<Button>Go</Button>` inside a `<Form>` to reproduce.

Use https://github.com/ide/react-native-button and define `var Button = require('react-native-button');` at top of your script.

**Comment by jucastilhoduarte** [comment]
Ok, I'll fix that today.

**Comment by jucastilhoduarte** [comment]
@niftylettuce issue fixed (https://github.com/julianocomg/react-native-form/commit/1c24d52cba4c9467b7b0c25b603950c6dbce54b4)

**Comment by niftylettuce** [comment]
awesome thank you @julianocomg!  works great.
