### ISSUE TITLE
Question: PickerIOS usage

### ISSUE THREAD

**Issue by tristangodfrey** [julianocomg/react-native-form#5]
First of all I love this package, great for reducing redundancy in my code.

I have a quick question about how `PickerIOS` is implemented with this package, because for some reason the selected value isn't working in my code. Could someone post an example of a functional `PickerIOS` with this package?

This is how I tried using it:

```
<Form ref="form">
  <PickerIOS name={this.props.name}>
    {
      this.props.options.map(function(option) {
        return (
          <PickerItemIOS
            key={option.id}
            value={option.id}
            label={option.name} />
        );
      })
    }
  </PickerIOS>
</Form>
```

Am I missing something? Thanks in advance.

**Comment by jucastilhoduarte** [comment]
@tristangodfrey Can you paste the error message here?

**Comment by tristangodfrey** [comment]
@julianocomg There is no error message, the problem I'm experiencing is that the picker isn't updating the "selected value", eg. when I try to test the picker in a simulator, after I drag to select a different value it just rolls back to the first option. I'm assuming because of a value link gone wrong somewhere. Could you post a working example of a picker with a few items? (using `react-native-form` ofc)

**Comment by julianocomg** [comment]
@tristangodfrey I can't find a solution for that problem now. The picker selected value is defined from the outside, the component needs to update with the new selectedValue prop, and the form doesn't have direct access to the child components props after the first mount :/

But PR's are welcome :)

**Comment by jucastilhoduarte** [comment]
@tristangodfrey Update to >=1.0 and be happy :)
