### ISSUE TITLE
Can't get values from custom field in release build

### ISSUE THREAD

**Issue by charpeni** [julianocomg/react-native-form#8]
I use this package with `TextInput` and a custom field `RadioButtons` from package [react-native-radio-buttons](https://github.com/ArnaudRinquin/react-native-radio-buttons).

Everything works fine in development, I can get all form values with `this.refs.form.getValues()`. 
When I build in release, `this.refs.form.getValues()` is only returns the values of `TextInput`, nothing from my custom field. 

Really weird behevior, any ideas? Maybe building in release do some optimization that break this feature.

**Comment by andreyvital** [comment]
Yes @charpeni. I can confirm the issue. I started looking into it.

**Comment by andreyvital** [comment]
It looks like the properties that this library relies on don't even are being set in release builds. Or they're stripped.

**Comment by jucastilhoduarte** [comment]
@charpeni Please update to version 2.0.+ and check out the README :+1:

**Comment by charpeni** [comment]
Thank you it works!
